### ISSUE TITLE
Can't migrate:down specific migration

### ISSUE THREAD

**Issue by cah-kangkung** [kysely-org/kysely-ctl#117]
`kysely migrate:down [OPTIONS] [MIGRATION_NAME]`

above command doesn't undo the specified [MIGRATION_NAME], it rolls back the latest migration up to that specified migration

**Comment by igalklebanov** [comment]
Hey 👋 

Migrating down to a specific migration means you're migrating the schema up to and including that migration.

**Comment by cah-kangkung** [comment]
oh my bad, i think i misunderstood the term _'rolling back'_, i thought that we could rollback only a single migration in the middle of all the migrations
