### ISSUE TITLE
Support for top-level await in ESModule

### ISSUE THREAD

**Issue by DominicRoyStang** [kysely-org/kysely-ctl#118]
When the kysely.config.ts file contains top-level await or imports a file that has top-level await, and the package.json `type` field is set to `module`, running `kysely migrate:make <migration name>` errors-out with the following message

>SyntaxError: await is only valid in async functions and the top level bodies of modules

In my case, this top-level await is used to fetch the database password from a secret manager.

Repro repository: https://github.com/DominicRoyStang/kysely-ctl-async-bug

**Comment by igalklebanov** [comment]
Hey 👋 

Thanks for raising this and providing a reproduction.

**Comment by igalklebanov** [comment]
Try this preview build:

```
npm i https://pkg.pr.new/kysely-org/kysely-ctl@07e409c
```

**Comment by noudadrichem** [comment]
Same. The new build works for me!

**Comment by igalklebanov** [comment]
Should be resolved in https://github.com/kysely-org/kysely-ctl/releases/tag/v0.10.0.
