### ISSUE TITLE
Why suggesting peer dependencies

### ISSUE THREAD

**Issue by pi0** [kysely-org/kysely-ctl#4]
Hi, I'm so glad that you are adopting unjs projects ❤️ 

I noticed something a little strange about usage though since you are advising to install needed depes as peer dependencies. May I ask the reasons behind it?

---

PS: Note sure if you also know about [jiti](https://jiti.unjs.io) project. Aside from top-level `await` support I like to know what were main limitations if you ever considered it (this dependency at least comes out of the box by c12 so at least will make install smaller)

**Comment by acro5piano** [comment]
I've been curious about it, too. As far as I know, `dependencies` is normally used over `peerDependencies` if these dependencies are mandatory, right?

**Comment by igalklebanov** [comment]
What are the pros/cons of either way? if both are installed automatically (when not `peerDependenciesMeta.optional: true`) by modern package managers.

The aim is to reduce install time and `node_modules` size by promoting the reuse of externals.

I might be missing something, and there might be more than just semantics here..

**Comment by igalklebanov** [comment]
@pi0 thank you! 🙏 

Released changes @ https://github.com/kysely-org/kysely-ctl/releases/tag/v0.6.0.
