### ISSUE TITLE
Use a unique db instance to perform scripts.

### ISSUE THREAD

**Issue by marcosrjjunior** [kysely-org/kysely-ctl#47]
- could we allow the defineConfig to accept the same **db** instance to perform scripts?

given a project where you have a db instance definition pointing to your desired dialect like usual,
we would have something like:

```js
import { defineConfig } from 'kysely-ctl'

export default defineConfig({
  db,
  migrations: {
     migrationFolder: path.join(__dirname, './src/db/migrations')
  },
})
```

Kysely already provides a clear and simple [Migrator class](https://kysely-org.github.io/kysely-apidoc/classes/Migrator.html) that is not related to any extra configuration or dependency.
Hopefully think this could make a bit easier to use like the [migration-cli](https://github.com/acro5piano/kysely-migration-cli/issues/23).

**Comment by igalklebanov** [comment]
Hey 👋 

> could we allow the defineConfig to accept the same db instance to perform scripts?

Yeah.

> Kysely already provides a clear and simple [Migrator class](https://kysely-org.github.io/kysely-apidoc/classes/Migrator.html) that is not related to any extra configuration or dependency.

How is that related?
