### ISSUE TITLE
defineConfig using --environment type issue with seedFolder

### ISSUE THREAD

**Issue by shane-js** [kysely-org/kysely-ctl#53]
Error:  "Type 'string' is not assignable to type 'undefined'.ts(2322)" seen when doing:

```
export default defineConfig({
  dialect: dialect,
  plugins: plugins,
  migrations: {
    migrationFolder: "./src/db/migrations",
  },
  $development: {
    seeds: {
      // @ts-expect-error for now igal on discord said he is looking into it
      seedFolder: "./src/db/seeds/development",
    },
  },
});
```

![image](https://github.com/kysely-org/kysely-ctl/assets/12244245/722cf313-ad56-4e11-9533-942bbe1ad9a2)

Additionally it also only lets you use the environment name strings found in c12's C12InputConfig interface but kysely-ctl's src/arguments/environment.mts has valueHint of 'prod | dev | test | ...' but you actually can't use those abbreviations for production and development without other typescript compilation error.

> Object literal may only specify known properties, and '$dev' does not exist in type '(C12InputConfig<KyselyCTLConfig<KyselyDialect>, ConfigLayerMeta> & KyselyCTLConfigBase & { ...; } & { ...; } & { ...; }) | ... 7 more ... | (C12InputConfig<...> & ... 3 more ... & { ...; })'.ts(2353)

![image](https://github.com/kysely-org/kysely-ctl/assets/12244245/affdf8e2-42fe-4e02-8e00-cb4b5a59ebbb)

Per @igalklebanov  review on discord issue is appropriate to raise on this.

**Comment by igalklebanov** [comment]
Hey 👋 

This should be addressed in https://github.com/kysely-org/kysely-ctl/releases/tag/v0.8.9.

C12 allows for custom environment names, not part of their predefined environment names list. You can use those in your config via:

```ts
{
  $env: {
    staging: {
      // ...
    }
  }
}
```
