### ISSUE TITLE
Potential incompatibility with a supabase hosted project

### ISSUE THREAD

**Issue by thenbe** [kysely-org/kysely-ctl#66]
Hi. First, thanks for creating kysely, the type inference has been awesome!

---

There's this issue I've been facing when using both of these at the same time:

- a supabase hosted project
- kysely-ctl migrations

The issue only happens when those two are used together. In isolation, the issue does not happen. In other words:

- a hosted supabase project works fine with vanilla sql migrations
- kysely-ctl migrations work fine with a vanilla postgres instance (it also works fine with the local supabase stack `pnpm supabase start`)

One crucial thing I should point out is that supabase hosted projects [do not grant](https://supabase.com/docs/guides/database/postgres/roles-superuser) superuser privileges. Would you happen to know if that could be a cause of incompatibility between the two? Could it be possible that kysely [tries to alter some default permissions or entities managed by Supabase](https://github.com/supabase/cli/issues/2472#issuecomment-2211806851)?

**Comment by igalklebanov** [comment]
Hey 👋 

What dialect are you using?

**Comment by thenbe** [comment]
[pg](https://github.com/kysely-org/kysely/blob/master/src/dialect/postgres/postgres-dialect.ts)

**Comment by igalklebanov** [comment]
The core PostgreSQL dialect executes the following:

```sql
select pg_advisory_xact_lock($1)
```
https://github.com/kysely-org/kysely/blob/master/src/dialect/postgres/postgres-adapter.ts#L23

...and runs migrations within a transaction.

Closing as this seems not related to this project, but to Kysely itself.
